name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      statuses: write
      contents: read
      packages: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven
      - name: Disable Testcontainers for Windows and MacOS
        run: echo "args=-P=no-testcontainers" >> "$GITHUB_ENV"
        shell: bash
        if: runner.os == 'windows' || runner.os == 'macos'
      - run: msiexec /i setup\wix\Bonjour64.msi /Quiet /Passive /NoRestart
        if: runner.os == 'windows'
      - uses: microsoft/setup-msbuild@v2
        if: runner.os == 'windows'
        with:
          msbuild-architecture: x64
      - name: "NuGet"
        if: runner.os == 'windows'
        env:
          NugetCredentials: "Username=${{ github.actor }};Password=${{ secrets.GITHUB_TOKEN }}"
        run: |
          echo "NuGetPackageSourceCredentials_gh-ikvmnet=${{ env.NugetCredentials }}" >> $env:GITHUB_ENV
          echo "NuGetPackageSourceCredentials_gh-iterate-ch=${{ env.NugetCredentials }}" >> $env:GITHUB_ENV
      - name: Build with Maven
        run: mvn --no-transfer-progress verify -DskipITs -DskipSign ${{ env.args }} --batch-mode -Drevision=0
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1.9.1
