name: Synchronize connection profiles

on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths:
            - 'profiles/*.cyberduckprofile'
jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Install Cyberduck CLI
                run: |
                    echo -e "deb https://s3.amazonaws.com/repo.deb.cyberduck.io stable main" | sudo tee /etc/apt/sources.list.d/cyberduck.list > /dev/null
                    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FE7097963FEFBE72
                    sudo apt-get update
                    sudo apt-get -y install duck
            -   name: Upload changed connection profiles to s3:/profiles.cyberduck.io
                run: |
                    scripts/sync-latest.sh .
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                working-directory: profiles
